apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "mysql-service"
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: PMA_ARBITRARY
              value: "1"
            - name: UPLOAD_LIMIT
              value: "512M"
            - name: MEMORY_LIMIT
              value: "512M"
            - name: MAX_EXECUTION_TIME
              value: "600"
          volumeMounts:
            - name: phpmyadmin-apache-config
              mountPath: /etc/apache2/conf-enabled/phpmyadmin.conf
              subPath: phpmyadmin.conf
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"
              cpu: "500m"
      volumes:
        - name: phpmyadmin-apache-config
          configMap:
            name: phpmyadmin-apache-config
