apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: oacarrillop/api-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4020
              name: https
          env:
            - name: NODE_ENV
              value: "desarrollo"
            - name: API_PORT
              value: "4020"
            - name: API_KEY_VALIDACION_LOCAL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: API_KEY_VALIDACION_LOCAL
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 4020
#              scheme: HTTPS
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            timeoutSeconds: 5
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 4020
#              scheme: HTTPS
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            timeoutSeconds: 3
